import { Toaster } from '@/components/ui/toaster';
import { SubLayout } from '@/layouts/SubLayout';
import { ThemeProvider } from '@/providers/ThemeProvider';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import localFont from 'next/font/local';
import './globals.css';
import { ClassNameMode } from '@/utils/classes';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900'
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900'
});

export const metadata: Metadata = {
    title: 'Base Next Tailwind',
    description: 'Generated by create next app'
};

export default async function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    const messages = await getMessages();
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={ClassNameMode.background(
                    `${geistSans.variable} ${geistMono.variable} antialiased transition-all duration-200`
                )}
            >
                <NextIntlClientProvider messages={messages}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <SubLayout>
                            {children}
                            <Toaster />
                        </SubLayout>
                    </ThemeProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
