name: Next CI Staging

on:
  push:
    branches:
      - "*"
      - "*/*"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node version
        uses: actions/setup-node@v4
        with:
          node-version: "21.x"

      - name: Install
        run: |
          npm ci

  build:
    runs-on: ubuntu-22.04
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build the app
        run: |
          npm run build
